/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guii;

import Admin.Admin;
import Admin.ReadAdmin;

import Admin.SendData;

import java.awt.Color;
import java.awt.Dialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private String name;
    private String myip;
    private String TotalPhysicalMemory;
    private String AvailablePhysicalMemory;
    private String LoadPercentage;

    public User(String username, String ip) {
        initComponents();
        setVisible(true);
        tabinfo.setBackground(Color.gray);
        //ShowOnScreen(0, this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.name = username;
        this.myip = ip;
        jLabel1.setText(name);
        jLabel1.setVerticalAlignment(JLabel.CENTER);
        jLabel1.setHorizontalAlignment(JLabel.CENTER);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        tabinfo = new javax.swing.JPanel();
        iinfo = new javax.swing.JLabel();
        tabfollow = new javax.swing.JPanel();
        ffollow = new javax.swing.JLabel();
        tabmanager = new javax.swing.JPanel();
        mmanager = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        GeneralInfo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CpuInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DiskInfo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        NetworkInfo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        RAMinfo = new javax.swing.JPanel();
        jLabelRAM = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        follow = new javax.swing.JPanel();
        jLabelDISK = new javax.swing.JLabel();
        jLabelCPU = new javax.swing.JLabel();
        jLabelPROCESS = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        jLabelMEMORY = new javax.swing.JLabel();
        manager = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tasklist = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        capscreen = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        shutdown = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        clipboard = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        keyslog = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User");
        setLocation(new java.awt.Point(50, 50));
        setSize(new java.awt.Dimension(50, 50));

        menu.setBackground(new java.awt.Color(23, 35, 51));

        tabinfo.setBackground(new java.awt.Color(23, 35, 51));
        tabinfo.setLayout(new java.awt.CardLayout());

        iinfo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        iinfo.setForeground(new java.awt.Color(255, 255, 255));
        iinfo.setText("SYSTEM INFORMATION");
        iinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked1(evt);
            }
        });
        tabinfo.add(iinfo, "card2");

        tabfollow.setBackground(new java.awt.Color(23, 35, 51));
        tabfollow.setPreferredSize(new java.awt.Dimension(121, 13));

        ffollow.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ffollow.setForeground(new java.awt.Color(255, 255, 255));
        ffollow.setText("MONITORING SYSTEM");
        ffollow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked1(evt);
            }
        });
        tabfollow.add(ffollow);

        tabmanager.setBackground(new java.awt.Color(23, 35, 51));
        tabmanager.setPreferredSize(new java.awt.Dimension(121, 13));
        tabmanager.setLayout(new java.awt.CardLayout());

        mmanager.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        mmanager.setForeground(new java.awt.Color(255, 255, 255));
        mmanager.setText("USER MANAGEMENT");
        mmanager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClicked1(evt);
            }
        });
        tabmanager.add(mmanager, "card2");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_find_user_male_100px.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 102));
        jLabel9.setText("Administrator");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("-------------------------------");

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabfollow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tabmanager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(tabinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabfollow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabmanager, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        content.setBackground(new java.awt.Color(71, 120, 197));

        main.setAutoscrolls(true);
        main.setPreferredSize(new java.awt.Dimension(650, 360));
        main.setLayout(new java.awt.CardLayout());

        info.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("SYSTEM INFORMATION");

        GeneralInfo.setBackground(new java.awt.Color(204, 204, 204));
        GeneralInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GeneralInfoMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("GENERAL INFORMATION");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_system_information_40px.png"))); // NOI18N

        javax.swing.GroupLayout GeneralInfoLayout = new javax.swing.GroupLayout(GeneralInfo);
        GeneralInfo.setLayout(GeneralInfoLayout);
        GeneralInfoLayout.setHorizontalGroup(
            GeneralInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GeneralInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralInfoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GeneralInfoLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        GeneralInfoLayout.setVerticalGroup(
            GeneralInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralInfoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        CpuInfo.setBackground(new java.awt.Color(204, 204, 204));
        CpuInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CpuInfoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CPU");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_workstation_40px.png"))); // NOI18N

        javax.swing.GroupLayout CpuInfoLayout = new javax.swing.GroupLayout(CpuInfo);
        CpuInfo.setLayout(CpuInfoLayout);
        CpuInfoLayout.setHorizontalGroup(
            CpuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CpuInfoLayout.createSequentialGroup()
                .addGroup(CpuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CpuInfoLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8))
                    .addGroup(CpuInfoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CpuInfoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(63, 63, 63))
        );
        CpuInfoLayout.setVerticalGroup(
            CpuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CpuInfoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );

        DiskInfo.setBackground(new java.awt.Color(204, 204, 204));
        DiskInfo.setPreferredSize(new java.awt.Dimension(151, 102));
        DiskInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiskInfoMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DISK");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_hdd_40px.png"))); // NOI18N

        javax.swing.GroupLayout DiskInfoLayout = new javax.swing.GroupLayout(DiskInfo);
        DiskInfo.setLayout(DiskInfoLayout);
        DiskInfoLayout.setHorizontalGroup(
            DiskInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiskInfoLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(DiskInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        DiskInfoLayout.setVerticalGroup(
            DiskInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DiskInfoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        NetworkInfo.setBackground(new java.awt.Color(204, 204, 204));
        NetworkInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NetworkInfoMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("NETWORK");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_internet_folder_40px.png"))); // NOI18N

        javax.swing.GroupLayout NetworkInfoLayout = new javax.swing.GroupLayout(NetworkInfo);
        NetworkInfo.setLayout(NetworkInfoLayout);
        NetworkInfoLayout.setHorizontalGroup(
            NetworkInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NetworkInfoLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(NetworkInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NetworkInfoLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NetworkInfoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(47, 47, 47))))
        );
        NetworkInfoLayout.setVerticalGroup(
            NetworkInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NetworkInfoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        RAMinfo.setBackground(new java.awt.Color(204, 204, 204));
        RAMinfo.setPreferredSize(new java.awt.Dimension(151, 102));
        RAMinfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RAMinfoMouseClicked(evt);
            }
        });

        jLabelRAM.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelRAM.setText("RAM");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_smartphone_ram_40px_1.png"))); // NOI18N

        javax.swing.GroupLayout RAMinfoLayout = new javax.swing.GroupLayout(RAMinfo);
        RAMinfo.setLayout(RAMinfoLayout);
        RAMinfoLayout.setHorizontalGroup(
            RAMinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RAMinfoLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(RAMinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RAMinfoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelRAM))
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        RAMinfoLayout.setVerticalGroup(
            RAMinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RAMinfoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jLabelRAM, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(GeneralInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DiskInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RAMinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoLayout.createSequentialGroup()
                        .addComponent(NetworkInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CpuInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addGap(39, 39, 39)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(GeneralInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DiskInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(RAMinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NetworkInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CpuInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main.add(info, "card2");

        jLabelDISK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_hdd_40px.png"))); // NOI18N
        jLabelDISK.setText("DISK");

        jLabelCPU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_workstation_40px.png"))); // NOI18N
        jLabelCPU.setText("CPU");
        jLabelCPU.setPreferredSize(new java.awt.Dimension(67, 40));

        jLabelPROCESS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_system_task_40px.png"))); // NOI18N
        jLabelPROCESS.setText("PROCESSES");
        jLabelPROCESS.setPreferredSize(new java.awt.Dimension(67, 40));

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_refresh_16px.png"))); // NOI18N
        refresh.setText("Refresh");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });

        jLabelMEMORY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_smartphone_ram_40px_1.png"))); // NOI18N
        jLabelMEMORY.setText("MEMORY");
        jLabelMEMORY.setPreferredSize(new java.awt.Dimension(67, 40));

        javax.swing.GroupLayout followLayout = new javax.swing.GroupLayout(follow);
        follow.setLayout(followLayout);
        followLayout.setHorizontalGroup(
            followLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, followLayout.createSequentialGroup()
                .addGap(568, 568, 568)
                .addComponent(refresh)
                .addGap(20, 20, 20))
            .addGroup(followLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(followLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDISK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCPU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPROCESS, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(jLabelMEMORY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        followLayout.setVerticalGroup(
            followLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(followLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(refresh)
                .addGap(33, 33, 33)
                .addComponent(jLabelDISK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPROCESS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelMEMORY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        main.add(follow, "card3");

        manager.setBackground(new java.awt.Color(255, 255, 255));
        manager.setAutoscrolls(true);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("USER MANAGEMENT");

        tasklist.setBackground(new java.awt.Color(204, 204, 204));
        tasklist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasklistMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Processes");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_services_40px.png"))); // NOI18N

        javax.swing.GroupLayout tasklistLayout = new javax.swing.GroupLayout(tasklist);
        tasklist.setLayout(tasklistLayout);
        tasklistLayout.setHorizontalGroup(
            tasklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasklistLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tasklistLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(31, 31, 31))
        );
        tasklistLayout.setVerticalGroup(
            tasklistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tasklistLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(23, 23, 23))
        );

        capscreen.setBackground(new java.awt.Color(204, 204, 204));
        capscreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                capscreenMouseClicked(evt);
            }
        });
        capscreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText(" Screen capture");
        capscreen.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_screenshot_40px.png"))); // NOI18N
        capscreen.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 19, -1, -1));

        logout.setBackground(new java.awt.Color(204, 204, 204));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Log Out");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_export_40px.png"))); // NOI18N

        javax.swing.GroupLayout logoutLayout = new javax.swing.GroupLayout(logout);
        logout.setLayout(logoutLayout);
        logoutLayout.setHorizontalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        logoutLayout.setVerticalGroup(
            logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(27, 27, 27))
        );

        shutdown.setBackground(new java.awt.Color(204, 204, 204));
        shutdown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shutdownMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Shut Down");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_shutdown_40px_3.png"))); // NOI18N

        javax.swing.GroupLayout shutdownLayout = new javax.swing.GroupLayout(shutdown);
        shutdown.setLayout(shutdownLayout);
        shutdownLayout.setHorizontalGroup(
            shutdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shutdownLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shutdownLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(33, 33, 33))
        );
        shutdownLayout.setVerticalGroup(
            shutdownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shutdownLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addGap(27, 27, 27))
        );

        clipboard.setBackground(new java.awt.Color(204, 204, 204));
        clipboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clipboardMouseClicked(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("ClipBoard");

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_inspection_40px_1.png"))); // NOI18N

        javax.swing.GroupLayout clipboardLayout = new javax.swing.GroupLayout(clipboard);
        clipboard.setLayout(clipboardLayout);
        clipboardLayout.setHorizontalGroup(
            clipboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clipboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(35, 35, 35))
            .addGroup(clipboardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel24)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        clipboardLayout.setVerticalGroup(
            clipboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clipboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addGap(25, 25, 25))
        );

        keyslog.setBackground(new java.awt.Color(204, 204, 204));
        keyslog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keyslogMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Record key");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_keyboard_40px.png"))); // NOI18N

        javax.swing.GroupLayout keyslogLayout = new javax.swing.GroupLayout(keyslog);
        keyslog.setLayout(keyslogLayout);
        keyslogLayout.setHorizontalGroup(
            keyslogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keyslogLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(keyslogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyslogLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyslogLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(20, 20, 20))))
        );
        keyslogLayout.setVerticalGroup(
            keyslogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyslogLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel25)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout managerLayout = new javax.swing.GroupLayout(manager);
        manager.setLayout(managerLayout);
        managerLayout.setHorizontalGroup(
            managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(managerLayout.createSequentialGroup()
                        .addGroup(managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(managerLayout.createSequentialGroup()
                                .addComponent(tasklist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(shutdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(managerLayout.createSequentialGroup()
                                .addComponent(clipboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(capscreen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(managerLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, managerLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(keyslog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        managerLayout.setVerticalGroup(
            managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel12)
                .addGap(31, 31, 31)
                .addGroup(managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tasklist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shutdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clipboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(capscreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keyslog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main.add(manager, "card4");

        title.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        main.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(846, 479));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void formatdata(String s) {
        String[] data = s.split("\n");
        int count = data.length;
        String[] memmory = data[1].split(":");
        TotalPhysicalMemory = memmory[1];
        String[] memmory1 = data[2].split(":");
        AvailablePhysicalMemory = memmory1[1];
        LoadPercentage = data[5];
        jLabelMEMORY.setText("LoadPercentage/Total Physical Memory : " + AvailablePhysicalMemory + " / " + TotalPhysicalMemory);
        jLabelCPU.setText("CPU   " + " " + LoadPercentage + "%");
        String tam = "";
        System.out.println("gui.User.formatdata()" + count);
        for (int i = 10; i < count - 1; i++) {
            tam = tam + data[i] + "\n";
        }
        jLabelDISK.setText("DISK   " + " " + tam);
        jLabelPROCESS.setText("NUMBER OF PROCESS   " + " " + data[count - 1]);
    }
    private void MouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClicked1
        // TODO add your handling code here:
        if (evt.getSource() == iinfo) {
            
            info.setVisible(true);
            follow.setVisible(false);
            manager.setVisible(false);
            tabinfo.setBackground(Color.gray);
            tabfollow.setBackground(new Color(23, 35, 51));
            tabmanager.setBackground(new Color(23, 35, 51));
        }
        // TODO add your handling code here:
        if (evt.getSource() == ffollow) {
            info.setVisible(false);
            follow.setVisible(true);
            manager.setVisible(false);
            tabfollow.setBackground(Color.gray);
            tabinfo.setBackground(new Color(23, 35, 51));
            tabmanager.setBackground(new Color(23, 35, 51));
            ReadAdmin.test = "";
            SendData data = new SendData(Admin.admin, myip, "follow");
            data.run();
            //String sms="Loading....";
            //Mess mess=new Mess(this, true, sms);
            while (ReadAdmin.test.equals("")) {
                //mess.setVisible(true);
                jLabel1.setText(name);
            }
            //mess.dispose();
            formatdata(ReadAdmin.test);

        }
        // TODO add your handling code here:
        if (evt.getSource() == mmanager) {
            
            info.setVisible(false);
            follow.setVisible(false);
            manager.setVisible(true);
            tabmanager.setBackground(Color.gray);
            tabfollow.setBackground(new Color(23, 35, 51));
            tabinfo.setBackground(new Color(23, 35, 51));
        }

    }//GEN-LAST:event_MouseClicked1

    private void GeneralInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GeneralInfoMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == GeneralInfo) {
            SendData data = new SendData(Admin.admin, myip, "systeminfo");
            data.run();
            GeneralInfo info;
            info = new GeneralInfo(name);
            info.setVisible(true);
            info.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
            
            

        }
    }//GEN-LAST:event_GeneralInfoMouseClicked

    private void tasklistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasklistMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == tasklist) {
            
            SendData data = new SendData(Admin.admin, myip, "tasklist");
            data.run();
//            while (!ReadAdmin.test.contains("tasklist")) {                
//                jLabel1.setText(name);
//            }
            Tasklist list;
            list = new Tasklist(name, myip);
            list.setVisible(true);

        }

    }//GEN-LAST:event_tasklistMouseClicked

    private void shutdownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shutdownMouseClicked

        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Do you want to Shut Down?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            System.out.println("YES.. Option Selected");
            SendData data = new SendData(Admin.admin, myip, "shutdown");
            data.run();
            SendData shutdown = new SendData(Admin.admin, myip, "shutdownuser");
            data.run();
            JOptionPane.showMessageDialog(this, "Successed");
            super.dispose();

            // JOptionPane.showMessageDialog(this,"Chờ client nó nhấn Ok rồi bên này mới trả về thông báo Successed hé :))");
        } else if (response == JOptionPane.NO_OPTION) {
            System.out.println("NO.. Option Selected");
        } else if (response == JOptionPane.CLOSED_OPTION) {
            System.out.println("CLOSE...");
        }

    }//GEN-LAST:event_shutdownMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Do you want to Log out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            System.out.println("YES.. Option Selected");
            System.out.println("YES.. Option Selected");
            SendData data = new SendData(Admin.admin, myip, "logout");
            data.run();

            JOptionPane.showMessageDialog(this, "Successed");
            super.dispose();
        } else if (response == JOptionPane.NO_OPTION) {
            System.out.println("NO.. Option Selected");
        } else if (response == JOptionPane.CLOSED_OPTION) {
            System.out.println("CLOSE...");
        }
    }//GEN-LAST:event_logoutMouseClicked

    private void DiskInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiskInfoMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == DiskInfo) {
            
            SendData data = new SendData(Admin.admin, myip, "disk");
            data.run();
            Disk disk;
            disk = new Disk(name);
            disk.setVisible(true);

        }
    }//GEN-LAST:event_DiskInfoMouseClicked

    private void CpuInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CpuInfoMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == CpuInfo) {
            
            SendData data = new SendData(Admin.admin, myip, "CPU");
            data.run();
            CPU cpu = new CPU(name);
            cpu.setVisible(true);

        }
    }//GEN-LAST:event_CpuInfoMouseClicked

    private void NetworkInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NetworkInfoMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == NetworkInfo) {
            
            SendData data = new SendData(Admin.admin, myip, "network");
            data.run();
            Network network = new Network(name);
            network.setVisible(true);

        }
    }//GEN-LAST:event_NetworkInfoMouseClicked

    private void RAMinfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RAMinfoMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == RAMinfo) {
            
            SendData data = new SendData(Admin.admin, myip, "RAM");
            data.run();
            RAM ram = new RAM(name);
            ram.setVisible(true);

        }
    }//GEN-LAST:event_RAMinfoMouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:
        ReadAdmin.test = "";
        SendData data = new SendData(Admin.admin, myip, "follow");
        data.run();
        //String sms="Loading....";
        // Mess mess=new Mess(this, true, sms);
        while (ReadAdmin.test.equals("")) {
            jLabel1.setText(name);
            // mess.setVisible(true);
        }
        //mess.dispose();
        formatdata(ReadAdmin.test);
    }//GEN-LAST:event_refreshMouseClicked

    private void capscreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_capscreenMouseClicked
        // TODO add your handling code here:
//        if (evt.getSource() == capscreen) {
//            SendData data = new SendData(Admin.admin, myip, "capscreen");
//            data.run();
//
//        }
       int response = JOptionPane.showConfirmDialog(this, "Chua lam", "Confirm", JOptionPane.CLOSED_OPTION);
            if (response == JOptionPane.CLOSED_OPTION) {
                System.out.println("CLOSE...");

            }
    }//GEN-LAST:event_capscreenMouseClicked

    private void clipboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clipboardMouseClicked
        // TODO add your handling code here:
        if (evt.getSource() == clipboard) {
            ReadAdmin.test = "";
            SendData data = new SendData(Admin.admin, myip, "clipboard");
            data.run();
            while (ReadAdmin.test.equals("")) {
                jLabel1.setText(name);
            }

                Clipboard clipboard = new Clipboard(name);
                clipboard.setVisible(true);


        }
    }//GEN-LAST:event_clipboardMouseClicked

    private void keyslogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keyslogMouseClicked
        // TODO add your handling code here:
        ReadAdmin.test = "";
        KeyLog keylog;
        keylog = new KeyLog(name);
        SendData data = new SendData(Admin.admin, myip,"keyslog");
        data.run();
            keylog.setVisible(true);


    }//GEN-LAST:event_keyslogMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CpuInfo;
    private javax.swing.JPanel DiskInfo;
    private javax.swing.JPanel GeneralInfo;
    private javax.swing.JPanel NetworkInfo;
    private javax.swing.JPanel RAMinfo;
    private javax.swing.JPanel capscreen;
    private javax.swing.JPanel clipboard;
    private javax.swing.JPanel content;
    private javax.swing.JLabel ffollow;
    private javax.swing.JPanel follow;
    private javax.swing.JLabel iinfo;
    private javax.swing.JPanel info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPU;
    private javax.swing.JLabel jLabelDISK;
    private javax.swing.JLabel jLabelMEMORY;
    private javax.swing.JLabel jLabelPROCESS;
    private javax.swing.JLabel jLabelRAM;
    private javax.swing.JPanel keyslog;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel main;
    private javax.swing.JPanel manager;
    private javax.swing.JPanel menu;
    private javax.swing.JLabel mmanager;
    private javax.swing.JLabel refresh;
    private javax.swing.JPanel shutdown;
    private javax.swing.JPanel tabfollow;
    private javax.swing.JPanel tabinfo;
    private javax.swing.JPanel tabmanager;
    private javax.swing.JPanel tasklist;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
